### Predict the Movie is going to win Start_Tech_Oscar or not by using Classification model

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Movie_classification.csv")

In [3]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [4]:
df.shape

(506, 19)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### Missing value imputation

In [6]:
df.Time_taken=df.Time_taken.fillna(df.Time_taken.mean())

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

### Dummy variable creation

In [8]:
df=pd.get_dummies(df)

In [9]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Avg_age_actors  Num_multiplex  \
0            7.995           7.94  ...              23            494   
1            7.470           7.44  ...              42            462   
2            7.515           7.44  ...              38            458   
3            7.020           8.26  ...              45            472   
4            7.070           8.26  ...              55            395   

   Collection  Start_Tech_Oscar  3D_available_NO  3D_available_YES  \
0       48000                 1                0                 1   
1       43200                 0                1                 0   
2       69400                 1                1                 0   
3       66800                 1                0                 1   
4       72400                 1                1                 0   

   Genre_Action  Genre_Comedy  Genre_Drama  Genre_Thriller  
0             0             0            0               1  
1             0             0            1               0  
2             0             1            0               0  
3             0             0            1               0  
4             0             0            1               0  

[5 rows x 23 columns]

In [10]:
del df['Genre_Action']

### x-y Split

In [11]:
x=df.loc[:,df.columns!='Start_Tech_Oscar']

In [12]:
x.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0            7.995           7.94  ...      109.60          223.840   
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_NO  \
0              23            494       48000                0   
1              42            462       43200                1   
2              38            458       69400                1   
3              45            472       66800                0   
4              55            395       72400                1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                 1             0            0               1  
1                 0             0            1               0  
2                 0             1            0               0  
3                 1             0            1               0  
4                 0             0            1               0  

[5 rows x 21 columns]

In [13]:
x.shape

(506, 21)

In [14]:
y=df['Start_Tech_Oscar']

In [15]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Start_Tech_Oscar, dtype: int64

In [16]:
y.shape

(506,)

### Train-Test-Split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [19]:
x_train.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
220            27.1618               67.40               0.493  38612.805   
71             23.1752               76.62               0.587  33113.355   
240            22.2658               64.86               0.572  38312.835   
6              21.7658               70.74               0.476  33396.660   
417           538.8120               91.20               0.321  29463.720   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
220         162.0               8.485                8.640            8.485   
71           91.0               7.280                7.400            7.290   
240         127.8               6.755                6.935            6.800   
6           140.1               7.065                7.265            7.150   
417         162.6               9.135                9.305            9.095   

     Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
220            8.670           8.52  ...      174.68          224.272   
71             7.455           8.16  ...      200.68          263.472   
240            6.840           8.68  ...      204.80          224.320   
6              7.400           8.96  ...      139.16          243.664   
417            9.165           6.96  ...      172.16          301.664   

     Avg_age_actors  Num_multiplex  Collection  3D_available_NO  \
220              23            536       53400                1   
71               46            400       43400                1   
240              24            387       54000                0   
6                41            522       45800                0   
417              60            589       20800                0   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
220                 0             0            0               1  
71                  0             0            0               0  
240                 1             1            0               0  
6                   1             0            0               1  
417                 1             0            0               0  

[5 rows x 21 columns]

In [20]:
x_train.shape

(404, 21)

In [21]:
x_test.shape

(102, 21)

In [22]:
y_train.shape

(404,)

In [23]:
y_test.shape

(102,)

### Standardizing data

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
sc= StandardScaler().fit(x_train)

In [26]:
x_train_std=sc.transform(x_train)

In [27]:
x_test_std=sc.transform(x_test)

In [28]:
x_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

In [29]:
x_test.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
329            21.3448               61.48               0.540  35179.815   
371           204.6460               91.20               0.369  34529.880   
219            22.2850               82.78               0.450  35402.015   
403           516.0340               91.20               0.307  29713.695   
78             21.1292               80.66               0.563  34618.760   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
329          90.7               7.320                7.460            7.275   
371         173.5               9.310                9.525            9.320   
219         165.9               8.175                8.375            8.315   
403         169.5               9.125                9.310            9.060   
78          127.2               7.330                7.500            7.450   

     Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
329            7.515           8.62  ...  111.040000          283.616   
371            9.505           7.96  ...  196.000000          268.000   
219            8.405           8.72  ...  123.200000          263.680   
403            9.100           6.96  ...  157.391498          301.328   
78             7.690           8.26  ...  176.480000          303.392   

     Avg_age_actors  Num_multiplex  Collection  3D_available_NO  \
329              53            452       45200                1   
371              25            609      100000                0   
219              21            561       46000                0   
403              40            677       16600                0   
78               53            377       42400                0   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
329                 0             1            0               0  
371                 1             1            0               0  
219                 1             1            0               0  
403                 1             0            0               1  
78                  1             0            1               0  

[5 rows x 21 columns]

### Training Classification Tree

In [44]:
from sklearn import svm

In [46]:
clf_svm=svm.SVC(kernel='linear',C=0.01)

In [47]:
clf_svm.fit(x_train_std,y_train)

SVC(C=0.01, kernel='linear')

### Predict value using trained model

In [48]:
y_test_pred=clf_svm.predict(x_test_std)

In [49]:
y_train_pred=clf_svm.predict(x_train_std)

In [50]:
y_test_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [55]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [56]:
confusion_matrix(y_test,y_test_pred)

array([[11, 33],
       [ 8, 50]], dtype=int64)

In [57]:
accuracy_score(y_test,y_test_pred)

0.5980392156862745

In [58]:
clf_svm.n_support_

array([186, 192])

In [59]:
from sklearn.model_selection import GridSearchCV

In [60]:
params={'C':(0.001,0.005,0.01,0.05,0.1,0.5,1,5,10,50,100,500)}

In [61]:
clf_svm=svm.SVC(kernel='linear')

In [64]:
svm_grid_lin=GridSearchCV(clf_svm,params,n_jobs=1,cv=10,verbose=1,scoring='accuracy')

In [65]:
svm_grid_lin.fit(x_train_std,y_train)

Fitting 10 folds for each of 12 candidates, totalling 120 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 120 out of 120 | elapsed:  2.1min finished


GridSearchCV(cv=10, estimator=SVC(kernel='linear'), n_jobs=1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500)},
             scoring='accuracy', verbose=1)

In [66]:
svm_grid_lin.best_params_

{'C': 0.1}

In [67]:
linsvm_clf=svm_grid_lin.best_estimator_

In [69]:
accuracy_score(y_test,linsvm_clf.predict(x_test_std))

0.5980392156862745